development:
  db_url: postgres://chryus:havana22@localhost/jasper-development

test:
  db_url: postgres://chryus:havana22@localhost/jasper-test

production:
  db_url: postgres://chryus:havana22@localhost/jasper-prouduction
  max_connections: 25